// ============================================================
// نظام إدارة التمويل - Operations Module (Operation Control Center)
// Version: 10.5.0
// v10.5.0: نظام التوريدات الدورية (Recurring Supplies):
//          - قسم التكرار في Modal (إنشاء/تعديل)
//          - cycle_number=1 للأم + end=start+interval-1 + profit_due=end+offset + next=end+1
//          - عرض الدورات + توليد المستحق + إيقاف/تفعيل التكرار
//          - أعمدة التكرار في select
// v10.4.0: P2-3 - منع حذف ممول له تمويل مستلم (funded>0)
// ============================================================
var OPERATIONS_STATE={search:'',filter:'',records:[],referenceCache:{clients:null,investors:null},currentOperationId:null,currentOperation:null,currentCalcData:null,currentFunding:null,currentProfits:null,currentFinancials:null};
function initOperations(){ registerScreenLoader('operations',loadOperations); }
async function loadOperations(){ if(!isSupabaseReady())return; showLoading(); try{
var r=await runQuery(function(){ var q=APP.supabase.from('operations').select('id, name, type, client_id, amount, expected_profit, final_profit, status, start_date, end_date, is_locked, is_archived, created_at, reference_number, company_profit_type, company_profit_value, parent_operation_id, cycle_number, is_recurring, recurring_active, recurrence_interval_days, recurring_until, profit_due_date, next_cycle_start, profit_due_offset_days').order('created_at',{ascending:false}); if(OPERATIONS_STATE.filter)q=q.eq('status',OPERATIONS_STATE.filter); if(OPERATIONS_STATE.search)q=q.or('name.ilike.%'+OPERATIONS_STATE.search+'%'); return q; },{context:'loadOperations',throwError:true});
var c=await loadClientsForOps(); var byId={}; (c||[]).forEach(function(x){byId[x.id]=x;}); var ops=r.data||[]; ops.forEach(function(o){o.client=byId[o.client_id]||null;}); OPERATIONS_STATE.records=ops; renderOperationsList();
} catch(e){ showToast(handleSupabaseError(e,'تحميل العمليات'),'error'); }  finally { hideLoading(); } }
async function loadClientsForOps(){ if(OPERATIONS_STATE.referenceCache.clients)return OPERATIONS_STATE.referenceCache.clients; var r=await runQuery(function(){return APP.supabase.from('clients').select('id, name, is_archived').eq('is_archived',false).order('name');},{context:'loadClientsForOps',throwError:true}); OPERATIONS_STATE.referenceCache.clients=r.data||[]; return OPERATIONS_STATE.referenceCache.clients; }
async function loadInvestorsForOps(){ if(OPERATIONS_STATE.referenceCache.investors)return OPERATIONS_STATE.referenceCache.investors; var r=await runQuery(function(){return APP.supabase.from('investors').select('id, name, is_archived').eq('is_archived',false).order('name');},{context:'loadInvestorsForOps',throwError:true}); OPERATIONS_STATE.referenceCache.investors=r.data||[]; return OPERATIONS_STATE.referenceCache.investors; }
function renderOperationsList(){ var c=document.getElementById('operationsTable'); if(!c)return; if(!OPERATIONS_STATE.records.length){c.innerHTML='<div class="empty-state">لا توجد عمليات</div>';return;}
var h='<table><thead><tr><th>الاسم</th><th>العميل</th><th>المبلغ</th><th>الحالة</th><th>النهاية</th><th>إجراءات</th></tr></thead><tbody>';
OPERATIONS_STATE.records.forEach(function(op){ var locked=op.is_locked||op.status==='completed'||op.status==='cancelled';
var recBadge=op.is_recurring?' 🔁':''; var cycBadge=op.parent_operation_id?' <span class="badge badge-draft">دورة '+(op.cycle_number||'')+'</span>':'';
h+='<tr><td><a href="#" data-action="openOperationDetails" data-param="'+op.id+'">'+escapeHtml(op.name)+'</a>'+recBadge+cycBadge+'</td><td>'+escapeHtml(op.client?op.client.name:'-')+'</td><td>'+formatMoney(op.amount)+'</td><td><span class="badge badge-'+op.status+'">'+getStatusText(op.status)+'</span></td><td>'+formatDate(op.end_date)+'</td><td class="actions-cell">'+(canEdit()?'<button class="btn btn-secondary btn-sm" data-action="editOperation" data-param="'+op.id+'">✏️</button>'+(locked?'':'<button class="btn btn-warning btn-sm" data-action="archiveOperation" data-param="'+op.id+'">📦</button>'):'')+'</td></tr>'; });
c.innerHTML=h+'</tbody></table>'; }
// ✅ v10.5.0: حقن قسم التكرار داخل Modal العملية (نمط Dynamic Injection)
function _ensureRecurringSection(){ var form=document.getElementById('operationForm'); if(!form)return; if(document.getElementById('opRecurringSection')){ _bindRecurringToggle(); return; }
var box=document.createElement('div'); box.id='opRecurringSection';
box.innerHTML='<div class="form-group"><label style="display:flex;align-items:center;gap:8px;"><input type="checkbox" id="opIsRecurring" style="width:auto;"> 🔁 توريد دوري</label></div>'+
'<div id="opRecurringFields" style="display:none;">'+
'<div class="form-row"><div class="form-group"><label>مدة الدورة (أيام) *</label><input type="number" id="opRecurrenceIntervalDays" min="1"></div>'+
'<div class="form-group"><label>استحقاق الربح بعد النهاية بـ (أيام)</label><input type="number" id="opProfitDueOffsetDays" min="0" value="1"></div></div>'+
'<div class="form-group"><label>حتى تاريخ (اختياري)</label><input type="date" id="opRecurringUntil"></div></div>';
var submit=form.querySelector('button[type="submit"]'); if(submit)form.insertBefore(box,submit); else form.appendChild(box);
_bindRecurringToggle(); }
function _bindRecurringToggle(){ var b=document.getElementById('opIsRecurring'); if(b&&!b.dataset.bound){ b.dataset.bound='1'; b.addEventListener('change',function(){ var f=document.getElementById('opRecurringFields'); if(f)f.style.display=b.checked?'block':'none'; }); } }
async function openOperationModal(id){ if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;} var t=document.getElementById('operationModalTitle'),i=document.getElementById('operationId'); if(!t||!i)return; await loadClientsForOps();
var cs=document.getElementById('opClient'); if(cs){ var o='<option value="">-- اختر العميل --</option>'; (OPERATIONS_STATE.referenceCache.clients||[]).forEach(function(x){o+='<option value="'+x.id+'">'+escapeHtml(x.name)+'</option>';}); cs.innerHTML=o; }
['opName','opAmount','opInvestorDisplayAmount','opExpectedProfit','opFinalProfit','opProfitApprovalDate','opGoogleDriveUrl','opCompanyProfitValue','opStartDate','opDurationDays','opEndDate','opNotes'].forEach(function(x){_setVal(x,'');}); _setVal('opType','financing'); _setVal('opStatus','draft');
_ensureRecurringSection();
var rb=document.getElementById('opIsRecurring'); if(rb)rb.checked=false; _setVal('opRecurrenceIntervalDays',''); _setVal('opProfitDueOffsetDays','1'); _setVal('opRecurringUntil',''); var rf=document.getElementById('opRecurringFields'); if(rf)rf.style.display='none';
if(id){ var r=await runQuery(function(){return APP.supabase.from('operations').select('*').eq('id',id).single();},{context:'openOperationModal',throwError:true}); var op=r.data; if(!op){showToast('العملية غير موجودة','error');return;} t.textContent='تعديل عملية'; i.value=op.id; _setVal('opName',op.name);_setVal('opType',op.type);_setVal('opClient',op.client_id);_setVal('opAmount',op.amount);_setVal('opInvestorDisplayAmount',op.investor_display_amount);_setVal('opExpectedProfit',op.expected_profit);_setVal('opFinalProfit',op.final_profit);_setVal('opProfitApprovalDate',formatDateForInput(op.profit_approval_date));_setVal('opGoogleDriveUrl',op.google_drive_url);_setVal('opCompanyProfitType',op.company_profit_type);_setVal('opCompanyProfitValue',op.company_profit_value);_setVal('opStartDate',formatDateForInput(op.start_date));_setVal('opDurationDays',op.duration_days);_setVal('opEndDate',formatDateForInput(op.end_date));_setVal('opStatus',op.status);_setVal('opNotes',op.notes);
if(rb){ rb.checked=!!op.is_recurring; var rf2=document.getElementById('opRecurringFields'); if(rf2)rf2.style.display=op.is_recurring?'block':'none'; }
_setVal('opRecurrenceIntervalDays',op.recurrence_interval_days); _setVal('opProfitDueOffsetDays',op.profit_due_offset_days!=null?op.profit_due_offset_days:1); _setVal('opRecurringUntil',op.recurring_until?formatDateForInput(op.recurring_until):''); }
else { t.textContent='إضافة عملية'; i.value=''; _setVal('opStartDate',getTodayDate()); }
openModal('operationModal'); }
function editOperation(id){ if(!id)id=OPERATIONS_STATE.currentOperationId; if(!id){showToast('❌ لا توجد عملية','error');return;} closeModal('operationDetailsModal'); openOperationModal(id); }
async function saveOperation(form,event){ if(event)event.preventDefault(); if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;} var id=_getVal('operationId');
var data={name:_getVal('opName').trim(),type:_getVal('opType'),client_id:_getVal('opClient')||null,amount:parseFloat(_getVal('opAmount'))||0,investor_display_amount:_getVal('opInvestorDisplayAmount')?parseFloat(_getVal('opInvestorDisplayAmount')):null,expected_profit:parseFloat(_getVal('opExpectedProfit'))||0,final_profit:parseFloat(_getVal('opFinalProfit'))||0,profit_approval_date:_getVal('opProfitApprovalDate')||null,google_drive_url:_getVal('opGoogleDriveUrl')||null,company_profit_type:_getVal('opCompanyProfitType')||null,company_profit_value:parseFloat(_getVal('opCompanyProfitValue'))||0,start_date:_getVal('opStartDate'),duration_days:parseInt(_getVal('opDurationDays'))||0,end_date:_getVal('opEndDate')||null,notes:_getVal('opNotes').trim()};
if(!data.name){showToast('❌ الاسم مطلوب','error');return;} if(!data.client_id){showToast('❌ اختر العميل','error');return;} if(!data.amount||data.amount<=0){showToast('❌ المبلغ غير صحيح','error');return;} if(!data.start_date){showToast('❌ تاريخ البداية مطلوب','error');return;} if(!data.end_date&&data.start_date&&data.duration_days>0)data.end_date=formatDateForInput(addDays(data.start_date,data.duration_days));
// ✅ v10.5.0: حقول التكرار
var isRec=!!(document.getElementById('opIsRecurring')&&document.getElementById('opIsRecurring').checked);
var intervalDays=parseInt(_getVal('opRecurrenceIntervalDays'))||0;
if(isRec&&intervalDays<=0){showToast('❌ مدة الدورة مطلوبة ويجب أن تكون أكبر من 0 (بالأيام) — لا توجد مدة افتراضية','error');return;}
data.is_recurring=isRec; data.recurrence_interval_days=isRec?intervalDays:null; data.profit_due_offset_days=parseInt(_getVal('opProfitDueOffsetDays'))||1; data.recurring_until=_getVal('opRecurringUntil')||null;
if(isRec&&!id){ data.cycle_number=1; data.recurring_active=true; if(!data.end_date&&data.start_date)data.end_date=formatDateForInput(addDays(data.start_date,intervalDays-1)); data.profit_due_date=data.end_date?formatDateForInput(addDays(data.end_date,data.profit_due_offset_days)):null; data.next_cycle_start=data.end_date?formatDateForInput(addDays(data.end_date,1)):null; }
if(isRec&&id){ data.recurring_active=(OPERATIONS_STATE.currentOperation&&OPERATIONS_STATE.currentOperation.recurring_active!==false); }
if(!isRec){ data.recurring_active=false; data.cycle_number=null; data.next_cycle_start=null; data.profit_due_date=null; }
showLoading(); try{
if(id){
var chk=await runQuery(function(){return APP.supabase.from('operations').select('is_locked, status').eq('id',id).single();},{context:'saveOp-check',throwError:true});
if(chk.data&&(chk.data.is_locked===true||chk.data.status==='completed'||chk.data.status==='cancelled')){ showToast('❌ العملية مقفلة/منتهية/ملغاة - لا يمكن التعديل','error'); hideLoading(); return; }
await runQuery(function(){return APP.supabase.from('operations').update(data).eq('id',id);},{context:'saveOp-upd',throwError:true}); _log('تعديل عملية','operation',id,null,JSON.stringify(data),'update'); showToast('✅ تم تحديث العملية','success');
} else { data.status='draft'; var r=await runQuery(function(){return APP.supabase.from('operations').insert(data).select();},{context:'saveOp-ins',throwError:true}); if(r.data&&r.data[0]){_log('إضافة عملية','operation',r.data[0].id,null,JSON.stringify(data),'create'); showToast('✅ تم إضافة العملية','success');} }
closeModal('operationModal'); loadOperations(); } catch(e){ showToast(handleSupabaseError(e,'حفظ العملية'),'error'); } finally { hideLoading(); } }
async function _buildCalcData(opId){ var r=await Promise.all([ runQuery(function(){return APP.supabase.from('operations').select('*').eq('id',opId).single();},{context:'calc-op',throwError:true}), runQuery(function(){return APP.supabase.from('operation_investors').select('id, investor_id, contribution, profit').eq('operation_id',opId);},{context:'calc-opinv',throwError:false}), runQuery(function(){return APP.supabase.from('transfers').select('id, type, purpose, operation_id, client_id, investor_id, amount, transfer_date').eq('operation_id',opId);},{context:'calc-trans',throwError:false}) ]);
var op=r[0].data||null,oi=r[1].data||[],ts=r[2].data||[]; var idx={operationsById:{},opInvestorsByOperation:{},transfersByOperation:{}}; if(op)idx.operationsById[op.id]=op; idx.opInvestorsByOperation[opId]=oi; idx.transfersByOperation[opId]=ts; return {__opId:opId,operations:op?[op]:[],operationInvestors:oi,transfers:ts,indexes:idx}; }
async function getOperationFinancials(opId){ var data=(OPERATIONS_STATE.currentCalcData&&OPERATIONS_STATE.currentCalcData.__opId===opId)?OPERATIONS_STATE.currentCalcData:await _buildCalcData(opId); var f=getOperationFunding(opId,data),p=getOperationProfits(opId,data); var inv={}; f.perInvestor.forEach(function(x){inv[x.investorId]={funded:x.funded,returned:x.returned,profitPaid:x.profitPaid};}); return {totalFunded:f.funded,totalReturned:p.capitalReturned,totalProfitPaid:p.investorDistributed,clientPaid:f.clientRepayment,investors:inv}; }
async function openOperationDetails(id){ if(!id)return; OPERATIONS_STATE.currentOperationId=id; showLoading(); try{
var cd=await _buildCalcData(id); OPERATIONS_STATE.currentCalcData=cd; var op=cd.operations[0]||null; if(!op){showToast('العملية غير موجودة','error');return;} OPERATIONS_STATE.currentOperation=op;
OPERATIONS_STATE.currentFunding=getOperationFunding(id,cd); OPERATIONS_STATE.currentProfits=getOperationProfits(id,cd); OPERATIONS_STATE.currentFinancials=await getOperationFinancials(id);
var cn=op.client_id?((await runQuery(function(){return APP.supabase.from('clients').select('name').eq('id',op.client_id).single();},{context:'opClient',throwError:false})).data||{}).name:'-';
_renderSummary(op,cn); _renderCoverage(op,getCoverage(id,cd)); _renderWorkflow(op,OPERATIONS_STATE.currentFunding); await _renderRecurringSection(op); _renderInvestorsTab(op,OPERATIONS_STATE.currentFunding); await loadOpTransfersTab(id); await loadOpTimelineTab(id);
var t=document.getElementById('opDetailsTitle'); if(t)t.textContent='تفاصيل: '+op.name; openModal('operationDetailsModal');
} catch(e){ showToast(handleSupabaseError(e,'فتح تفاصيل العملية'),'error'); } finally { hideLoading(); } }
// ✅ v10.5.0: قسم الدورات في تفاصيل العملية
async function _renderRecurringSection(op){ var g=document.getElementById('opSummaryGrid'); if(!g)return; var old=document.getElementById('opRecurringCard'); if(old)old.remove();
var host=document.createElement('div'); host.id='opRecurringCard'; g.parentNode.insertBefore(host,g.nextSibling);
if(op.parent_operation_id){ host.innerHTML='<div class="warning-box">هذه دورة رقم '+(op.cycle_number||'-')+' من عملية متكررة — <a href="#" data-action="openOperationDetails" data-param="'+op.parent_operation_id+'">فتح العملية الأم</a></div>'; return; }
if(!op.is_recurring){ host.innerHTML=''; return; }
var cyc=await runQuery(function(){return APP.supabase.from('operations').select('id,cycle_number,start_date,end_date,profit_due_date,status').eq('parent_operation_id',op.id).order('cycle_number');},{context:'recurring-cycles',throwError:false});
var list=cyc.data||[]; var nextDue=null; list.forEach(function(c){ if(c.status==='active'&&c.profit_due_date&&(!nextDue||c.profit_due_date<nextDue))nextDue=c.profit_due_date; });
var h='<div style="background:#eef2ff;border:1px solid #c7d2fe;border-radius:12px;padding:14px;margin:12px 0;">';
h+='<strong>🔁 توريد دوري</strong> · كل '+op.recurrence_interval_days+' يوم · الدورات: '+(list.length+1)+' · '+(op.recurring_active?'نشط':'متوقف');
if(nextDue)h+=' · الربح القادم: '+formatDate(nextDue);
if(canEdit()){ h+='<div style="margin-top:8px;display:flex;gap:8px;flex-wrap:wrap;"><button class="btn btn-primary btn-sm" data-action="generateNextCycle" data-param="'+op.id+'">⚙️ توليد الدورة التالية</button>';
h+= op.recurring_active ? '<button class="btn btn-warning btn-sm" data-action="stopRecurring" data-param="'+op.id+'">⏸ إيقاف التكرار</button>' : '<button class="btn btn-success btn-sm" data-action="startRecurring" data-param="'+op.id+'">▶ تفعيل التكرار</button>'; h+='</div>'; }
h+='<div class="table-scroll" style="margin-top:10px;"><table><thead><tr><th>الدورة</th><th>البداية</th><th>النهاية</th><th>استحقاق الربح</th><th>الحالة</th><th></th></tr></thead><tbody>';
h+='<tr><td>1 (الأم)</td><td>'+formatDate(op.start_date)+'</td><td>'+formatDate(op.end_date)+'</td><td>'+formatDate(op.profit_due_date)+'</td><td>'+getStatusText(op.status)+'</td><td></td></tr>';
list.forEach(function(c){ h+='<tr><td>'+c.cycle_number+'</td><td>'+formatDate(c.start_date)+'</td><td>'+formatDate(c.end_date)+'</td><td>'+formatDate(c.profit_due_date)+'</td><td>'+getStatusText(c.status)+'</td><td><a href="#" data-action="openOperationDetails" data-param="'+c.id+'">فتح</a></td></tr>'; });
h+='</tbody></table></div></div>'; host.innerHTML=h; }
// ✅ v10.5.0: توليد/إيقاف/تفعيل
async function generateNextCycle(opId){ if(!canEdit())return; showLoading(); try{ var r=await APP.supabase.rpc('admin_generate_cycles'); showToast('✅ تم توليد '+(r.data||0)+' دورة','success'); await openOperationDetails(opId); }catch(e){ showToast('❌ '+e.message,'error'); } finally{ hideLoading(); } }
async function stopRecurring(opId){ if(!canEdit())return; if(!confirmAction('⏸ إيقاف التكرار؟ لن تُولَّد دورات جديدة.'))return; await runQuery(function(){return APP.supabase.from('operations').update({recurring_active:false}).eq('id',opId);},{context:'stopRec',throwError:true}); showToast('تم إيقاف التكرار','success'); await openOperationDetails(opId); }
async function startRecurring(opId){ if(!canEdit())return; await runQuery(function(){return APP.supabase.from('operations').update({recurring_active:true}).eq('id',opId);},{context:'startRec',throwError:true}); showToast('تم تفعيل التكرار','success'); await openOperationDetails(opId); }
function _renderSummary(op,cn){ var g=document.getElementById('opSummaryGrid'); if(!g)return; g.innerHTML='<div class="summary-item"><label>العميل</label><div class="val">'+escapeHtml(cn||'-')+'</div></div><div class="summary-item"><label>قيمة العملية</label><div class="val blue">'+formatMoney(op.amount)+'</div></div><div class="summary-item"><label>الربح المتوقع</label><div class="val orange">'+formatMoney(op.expected_profit||0)+'</div></div><div class="summary-item"><label>الربح النهائي</label><div class="val green">'+formatMoney(op.final_profit||0)+'</div></div><div class="summary-item"><label>الحالة</label><div class="val"><span class="badge badge-'+op.status+'">'+getStatusText(op.status)+'</span></div></div><div class="summary-item"><label>النهاية</label><div class="val">'+formatDate(op.end_date)+'</div></div>'+(op.is_locked?'<div class="summary-item"><label>القفل</label><div class="val red">🔒 مقفلة</div></div>':''); }
function _renderCoverage(op,cov){ var el=document.getElementById('opCoverageCard'); if(!el){ var g=document.getElementById('opSummaryGrid'); if(!g)return; el=document.createElement('div'); el.id='opCoverageCard'; g.parentNode.insertBefore(el,g.nextSibling); } var pct=Math.round(cov.fundedCoverage); var ready=cov.funded>=cov.required&&cov.required>0; el.innerHTML='<div style="background:#f8fafc;border-radius:10px;padding:16px;margin:12px 0;"><div style="display:flex;justify-content:space-between;margin-bottom:8px;"><strong>تغطية العملية</strong><span style="font-weight:700;color:'+(ready?'#10b981':'#f59e0b')+';">'+pct+'%</span></div><div style="background:#e2e8f0;border-radius:10px;height:18px;overflow:hidden;"><div style="background:'+(ready?'#10b981':'#667eea')+';height:100%;width:'+Math.min(100,pct)+'%;"></div></div><div style="display:flex;justify-content:space-between;margin-top:8px;font-size:.85rem;color:#64748b;"><span>متعهد '+formatMoney(cov.committed)+'</span><span>مستلم '+formatMoney(cov.funded)+'</span><span>مطلوب '+formatMoney(cov.required)+'</span></div></div>'; }
function _renderWorkflow(op,f){ var w=document.getElementById('workflowActions'); if(!w)return; if(!canEdit()){w.style.display='none';return;} w.style.display='flex'; var ready=f.funded>=f.required&&f.required>0; var h='';
if(op.status==='draft'){ h+='<button class="btn btn-primary" data-action="opActivate" '+(ready?'':'disabled style="opacity:.5;"')+'>🚀 تفعيل</button><button class="btn btn-success" data-action="opApproveProfit">📊 اعتماد الأرباح</button>'; }
else if(op.status==='active'&&!op.is_locked){ h+='<button class="btn btn-info" data-action="opFundClient">💵 تمويل العميل</button><button class="btn btn-info" data-action="opClientPayment">💰 دفعة من العميل</button><button class="btn btn-success" data-action="opDistributeProfit">📊 توزيع الأرباح</button><button class="btn btn-warning" data-action="opReturnCapital">🔄 إرجاع رأس مال</button><button class="btn btn-primary" data-action="opComplete">✅ إنهاء</button>'; }
if(op.is_locked||op.status==='completed') h+='<button class="btn btn-secondary" data-action="opUnlock">🔓 فتح القفل</button>';
w.innerHTML=h; }
function _renderInvestorsTab(op,f){ var c=document.getElementById('opInvestorsList'); if(!c)return; if(!f.perInvestor.length){c.innerHTML='<div class="empty-state">لا يوجد ممولين</div>';return;} var names={}; (OPERATIONS_STATE.referenceCache.investors||[]).forEach(function(x){names[x.id]=x.name;});
var h='<table><thead><tr><th>الممول</th><th>المتعهد</th><th>المستلم</th><th>المتبقي</th><th>الربح</th><th>إجراءات</th></tr></thead><tbody>';
f.perInvestor.forEach(function(pi){ h+='<tr><td>'+escapeHtml(names[pi.investorId]||'-')+'</td><td>'+formatMoney(pi.committed)+'</td><td>'+formatMoney(pi.funded)+'</td><td>'+formatMoney(pi.remaining)+'</td><td>'+formatMoney(pi.profit)+'</td><td class="actions-cell">'+((canEdit()&&pi.remaining>0)?'<button class="btn btn-success btn-sm" data-action="opReceiveContribution" data-param="'+pi.investorId+'">💸 استلام</button>':'')+'<button class="btn btn-secondary btn-sm" data-action="openEditOpInvestor" data-param="'+pi.opInvestorId+'">✏️</button><button class="btn btn-danger btn-sm" data-action="deleteOpInvestor" data-param="'+pi.opInvestorId+'">🗑️</button></td></tr>'; });
c.innerHTML=h+'</tbody></table>'; }
async function openAddInvestorToOp(){ if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;} if(!OPERATIONS_STATE.currentOperationId){showToast('❌ افتح العملية','error');return;} var op=OPERATIONS_STATE.currentOperation; if(op&&(op.is_locked||op.status==='completed'||op.status==='cancelled')){showToast('❌ العملية مقفلة/منتهية','error');return;} await loadInvestorsForOps(); var s=document.getElementById('newOpInvestorId'); if(s){ var o='<option value="">-- اختر الممول --</option>'; (OPERATIONS_STATE.referenceCache.investors||[]).forEach(function(x){o+='<option value="'+x.id+'">'+escapeHtml(x.name)+'</option>';}); s.innerHTML=o; } _setVal('newOpInvestorContribution',''); _setVal('newOpInvestorProfit',''); openModal('addInvestorToOpModal'); }
async function saveOpInvestor(form,event){  if(event)event.preventDefault(); if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;} var opId=OPERATIONS_STATE.currentOperationId,op=OPERATIONS_STATE.currentOperation; if(op&&(op.is_locked||op.status==='completed'||op.status==='cancelled')){showToast('❌ مقفلة/منتهية','error');return;} var inv=_getVal('newOpInvestorId'),con=parseFloat(_getVal('newOpInvestorContribution'))||0,pr=parseFloat(_getVal('newOpInvestorProfit'))||0; if(!inv){showToast('❌ اختر الممول','error');return;} if(con<=0){showToast('❌ المساهمة غير صحيحة','error');return;}
var dup=await runQuery(function(){return APP.supabase.from('operation_investors').select('id').eq('operation_id',opId).eq('investor_id',inv).limit(1);},{context:'saveOpInvestor-dup',throwError:true});
if(dup.data&&dup.data.length){ showToast('❌ هذا الممول مضاف بالفعل للعملية','error'); return; }
showLoading(); try{ var r=await runQuery(function(){return APP.supabase.from('operation_investors').insert({operation_id:opId,investor_id:inv,contribution:con,profit:pr}).select();},{context:'saveOpInvestor',throwError:true}); _log('إضافة ممول','operation_investor',r.data[0].id,null,JSON.stringify({investor_id:inv,contribution:con}),'create'); closeModal('addInvestorToOpModal'); showToast('✅ تم إضافة الممول','success'); _openDynamicModal('استلام المساهمة','<p>هل تم استلام '+formatMoney(con)+'؟</p><div style="display:flex;gap:10px;"><button type="button" class="btn btn-success btn-block" data-action="opReceiveContribution" data-param="'+inv+'">💸 نعم</button><button type="button" class="btn btn-secondary btn-block" data-action="closeModal" data-modal="opDynamicModal">لاحقاً</button></div>',null,null); await openOperationDetails(opId); } catch(e){ showToast(handleSupabaseError(e,'إضافة الممول'),'error'); } finally { hideLoading(); } }
async function openEditOpInvestor(recId){ if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;} var op=OPERATIONS_STATE.currentOperation; if(op&&(op.is_locked||op.status==='completed'||op.status==='cancelled')){showToast('❌ مقفلة/منتهية','error');return;} var r=await runQuery(function(){return APP.supabase.from('operation_investors').select('*').eq('id',recId).single();},{context:'editOpInvestor',throwError:true}); var rec=r.data; if(!rec){showToast('❌ غير موجود','error');return;} _setVal('editOpInvestorId',rec.id); _setVal('editOpInvestorContribution',rec.contribution); _setVal('editOpInvestorProfit',rec.profit); openModal('editOpInvestorModal'); }
async function updateOpInvestor(form,event){ if(event)event.preventDefault(); if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;} var recId=_getVal('editOpInvestorId'),con=parseFloat(_getVal('editOpInvestorContribution'))||0,pr=parseFloat(_getVal('editOpInvestorProfit'))||0; if(!recId||con<=0){showToast('❌ بيانات غير صحيحة','error');return;} var op=OPERATIONS_STATE.currentOperation; if(op&&(op.is_locked||op.status==='completed'||op.status==='cancelled')){showToast('❌ مقفلة/منتهية','error');return;} var f=OPERATIONS_STATE.currentFunding; var pi=null; f.perInvestor.forEach(function(x){if(x.opInvestorId===recId)pi=x;}); if(pi&&con<pi.funded-0.01){showToast('❌ لا يمكن خفض التعهد تحت المستلم','error');return;} showLoading(); try{ await runQuery(function(){return APP.supabase.from('operation_investors').update({contribution:con,profit:pr}).eq('id',recId);},{context:'updateOpInvestor',throwError:true}); _log('تعديل مساهمة','operation_investor',recId,null,JSON.stringify({contribution:con,profit:pr}),'update'); closeModal('editOpInvestorModal'); showToast('✅ تم التحديث','success'); await openOperationDetails(OPERATIONS_STATE.currentOperationId); } catch(e){ showToast(handleSupabaseError(e,'تحديث المساهمة'),'error'); } finally { hideLoading(); } }
async function deleteOpInvestor(recId){
if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;}
var recR=await runQuery(function(){return APP.supabase.from('operation_investors').select('*').eq('id',recId).single();},{context:'delOpInvestor-rec',throwError:true});
var rec=recR.data; if(!rec){showToast('❌ السجل غير موجود','error');return;}
var cd=await _buildCalcData(rec.operation_id);
var op=cd.operations[0]||null;
if(op&&(op.is_locked||op.status==='completed'||op.status==='cancelled')){showToast('❌ العملية مقفلة/منتهية','error');return;}
var f=getOperationFunding(rec.operation_id,cd);
var pi=null; f.perInvestor.forEach(function(x){if(x.investorId===rec.investor_id)pi=x;});
if(pi&&pi.funded>0.01){ showToast('❌ لا يمكن حذف الممول بعد استلام أي مساهمة. يوجد تمويل مستلم بالفعل.','error'); return; }
if(!confirmDelete('هذا الممول'))return;
showLoading(); try{ await runQuery(function(){return APP.supabase.from('operation_investors').delete().eq('id',recId);},{context:'delOpInvestor',throwError:true}); _log('حذف ممول','operation_investor',recId,null,null,'delete'); showToast('✅ تم الحذف','success'); await openOperationDetails(OPERATIONS_STATE.currentOperationId); } catch(e){ showToast(handleSupabaseError(e,'حذف الممول'),'error'); } finally { hideLoading(); } }
async function opReceiveContribution(invId){
if(!canEdit()){ showToast('❌ لا توجد صلاحية','error'); return; }
var opId=OPERATIONS_STATE.currentOperationId,op=OPERATIONS_STATE.currentOperation; if(!op){showToast('❌ افتح العملية','error');return;} if(op.is_locked){showToast('❌ مقفلة','error');return;} if(op.status!=='draft'&&op.status!=='active'){showToast('❌ الحالة لا تسمح','error');return;} var f=OPERATIONS_STATE.currentFunding; var pi=null; f.perInvestor.forEach(function(x){if(x.investorId===invId)pi=x;}); if(!pi){showToast('❌ غير مرتبط','error');return;} if(pi.remaining<=0){showToast('✅ مستلم بالكامل','success');return;} if(!confirmAction('💸 استلام '+formatMoney(pi.remaining)+'؟'))return; showLoading(); try{ await _createTransfer({type:'investor_to_company',purpose:'capital_funding',operation_id:opId,investor_id:invId,client_id:null,amount:pi.remaining,transfer_date:getTodayDate(),notes:'استلام مساهمة - '+op.name},'استلام مساهمة'); closeModal('opDynamicModal'); showToast('✅ تم الاستلام','success'); await openOperationDetails(opId); } catch(e){ showToast(handleSupabaseError(e,'الاستلام'),'error'); }  finally { hideLoading(); } }
async function opActivate(){
if(!canEdit()){ showToast('❌ لا توجد صلاحية','error'); return; }
var opId=OPERATIONS_STATE.currentOperationId,op=OPERATIONS_STATE.currentOperation; if(!op){showToast('❌ افتح العملية','error');return;} if(op.is_locked){showToast('❌ مقفلة','error');return;} if(op.status!=='draft'){showToast('❌ ليست مسودة','error');return;} var f=OPERATIONS_STATE.currentFunding; if(f.funded<f.required){showToast('❌ التمويل المستلم '+formatMoney(f.funded)+' من '+formatMoney(f.required),'error');return;} if(!confirmAction('🚀 تفعيل العملية؟'))return; showLoading(); try{ await runQuery(function(){return APP.supabase.from('operations').update({status:'active'}).eq('id',opId);},{context:'opActivate',throwError:true}); _log('تفعيل عملية','operation',opId,null,'{"status":"active"}','workflow'); showToast('✅ تم التفعيل','success'); await openOperationDetails(opId); } catch(e){ showToast(handleSupabaseError(e,'التفعيل'),'error'); } finally { hideLoading();  } }
function opFundClient(){ var opId=OPERATIONS_STATE.currentOperationId,op=OPERATIONS_STATE.currentOperation; if(!op){showToast('❌ افتح العملية','error');return;} if(op.is_locked){showToast('❌ مقفلة','error');return;} if(op.status!=='active'){showToast('❌ غير نشطة','error');return;} if(!op.client_id){showToast('❌ لا يوجد عميل','error');return;} var f=OPERATIONS_STATE.currentFunding; if(f.remainingClientFunding<=0){showToast('✅ مموّل بالكامل','success');return;} _openDynamicModal('💵 تمويل العميل','<div class="form-group"><label>المبلغ</label><input type="number" id="opFundAmount" value="'+f.remainingClientFunding+'" step="0.01"></div><div class="form-group"><label>التاريخ</label><input type="date" id="opFundDate" value="'+getTodayDate()+'"></div>','submitOpAction','تحويل'); document.getElementById('opDynamicActionType').value='client_funding'; }
function opClientPayment(){ var op=OPERATIONS_STATE.currentOperation; if(!op){showToast('❌ افتح العملية','error');return;} if(op.is_locked){showToast('❌ مقفلة','error');return;} if(op.status!=='active'){showToast('❌ غير نشطة','error');return;} var p=OPERATIONS_STATE.currentProfits; _openDynamicModal('💰 دفعة من العميل','<p>المستحق '+formatMoney(p.clientDueTotal)+' · المسدد '+formatMoney(p.clientRepayment)+' · المتبقي '+formatMoney(p.clientOutstanding)+'</p><div class="form-group"><label>المبلغ</label><input type="number" id="opPayAmount" step="0.01"></div><div class="form-group"><label>التاريخ</label><input type="date" id="opPayDate" value="'+getTodayDate()+'"></div>','submitOpAction','تسجيل'); document.getElementById('opDynamicActionType').value='client_repayment'; }
function opApproveProfit(){ var op=OPERATIONS_STATE.currentOperation; if(!op){showToast('❌ افتح العملية','error');return;} if(op.is_locked){showToast('❌ مقفلة','error');return;} _openDynamicModal('📊 اعتماد الأرباح','<div class="form-group"><label>الربح النهائي</label><input type="number" id="opFinalProfitInput" value="'+(op.final_profit||'')+'" step="0.01"></div><div class="form-group"><label>تاريخ الاعتماد</label><input type="date" id="opApproveDate" value="'+getTodayDate()+'"></div>','submitOpAction','اعتماد'); document.getElementById('opDynamicActionType').value='approve_profit'; }
function opDistributeProfit(){ var op=OPERATIONS_STATE.currentOperation; if(!op){showToast('❌ افتح العملية','error');return;} if(op.is_locked){showToast('❌ مقفلة','error');return;} if(op.status!=='active'){showToast('❌ غير نشطة','error');return;}
var isFin=(typeof _isFinancing==='function')?_isFinancing(op):(op.type==='financing');
if(!isFin&&(!op.final_profit||!op.profit_approval_date)){ showToast('❌ لا يمكن توزيع الأرباح قبل اعتماد الربح النهائي','error'); return; }
var f=OPERATIONS_STATE.currentFunding; var names={}; (OPERATIONS_STATE.referenceCache.investors||[]).forEach(function(x){names[x.id]=x.name;}); var rows='',any=false;
f.perInvestor.forEach(function(pi){ if(pi.profit>0)any=true; rows+='<div class="form-group"><label>'+escapeHtml(names[pi.investorId]||'ممول')+' (متبقي '+formatMoney(pi.remainingProfit)+')</label><input type="number" name="pd_'+pi.investorId+'" value="'+(pi.remainingProfit>0?pi.remainingProfit:'')+'" step="0.01"></div>'; });
if(!any)rows='<p>لا توجد أرباح محددة.</p>'; _openDynamicModal('📊 توزيع الأرباح',rows,'submitOpAction','توزيع'); document.getElementById('opDynamicActionType').value='profit_distribution'; }
function opReturnCapital(){ var op=OPERATIONS_STATE.currentOperation; if(!op){showToast('❌ افتح العملية','error');return;} if(op.is_locked){showToast('❌ مقفلة','error');return;} if(op.status!=='active'){showToast('❌ غير نشطة','error');return;} var f=OPERATIONS_STATE.currentFunding; var names={}; (OPERATIONS_STATE.referenceCache.investors||[]).forEach(function(x){names[x.id]=x.name;}); var rows=''; f.perInvestor.forEach(function(pi){ rows+='<div class="form-group"><label>'+escapeHtml(names[pi.investorId]||'ممول')+' (متبقي '+formatMoney(pi.remainingCapital)+')</label><input type="number" name="cr_'+pi.investorId+'" value="'+(pi.remainingCapital>0?pi.remainingCapital:'')+'" step="0.01"></div>'; }); _openDynamicModal('🔄 إرجاع رأس المال',rows,'submitOpAction','إرجاع'); document.getElementById('opDynamicActionType').value='capital_return'; }
async function opComplete(){
if(!canEdit()){ showToast('❌ لا توجد صلاحية','error'); return; }
var opId=OPERATIONS_STATE.currentOperationId,op=OPERATIONS_STATE.currentOperation; if(!op){showToast('❌ افتح العملية','error');return;} if(op.status!=='active'){showToast('❌ غير نشطة','error');return;}
var f=OPERATIONS_STATE.currentFunding,p=OPERATIONS_STATE.currentProfits; var msgs=[];
if(p&&p.investorRemaining>0.01)msgs.push('ربح ممولين مستحق '+formatMoney(p.investorRemaining));
var capOut=f?Math.max(0,f.funded-f.capitalReturned):0; if(capOut>0.01)msgs.push('رأس مال مستحق '+formatMoney(capOut));
if(p&&p.clientOutstanding>0.01)msgs.push('مبلغ مستحق من العميل '+formatMoney(p.clientOutstanding));
var base='✅ إنهاء العملية وقفلها؟'; if(msgs.length)base='تنبيه: العملية ما زال عليها:\n- '+msgs.join('\n- ')+'\n\nهل تريد إغلاق العملية؟';
if(!confirmAction(base))return; showLoading(); try{ await runQuery(function(){return APP.supabase.from('operations').update({status:'completed',is_locked:true}).eq('id',opId);},{context:'opComplete',throwError:true}); _log('إنهاء عملية','operation',opId,null,'{"status":"completed"}','workflow'); showToast('✅ تم الإنهاء','success'); await openOperationDetails(opId); } catch(e){ showToast(handleSupabaseError(e,'الإنهاء'),'error'); } finally { hideLoading();  } }
async function opUnlock(){
if(!canEdit()){ showToast('❌ لا توجد صلاحية','error'); return; }
var op=OPERATIONS_STATE.currentOperation; if(!op){showToast('❌ افتح العملية','error');return;}
var msg='🔓 فتح القفل؟';
if(op.status==='completed') msg='تنبيه: فتح القفل سيعيد العملية إلى Active لتسويتها.\nلا تُعدَّل أي تحويلات أو أرقام.\nهل تريد المتابعة؟';
if(!confirmAction(msg))return; showLoading(); try{
var upd=(op.status==='completed')?{status:'active',is_locked:false}:{is_locked:false};
await runQuery(function(){return APP.supabase.from('operations').update(upd).eq('id',OPERATIONS_STATE.currentOperationId);},{context:'opUnlock',throwError:true});
_log('فتح قفل عملية','operation',OPERATIONS_STATE.currentOperationId,null,JSON.stringify(upd),'workflow'); showToast('✅ تم فتح القفل','success'); await openOperationDetails(OPERATIONS_STATE.currentOperationId);
} catch(e){ showToast(handleSupabaseError(e,'فتح القفل'),'error'); } finally { hideLoading(); } }
async function submitOpAction(form,event){ if(event)event.preventDefault(); if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;} var opId=OPERATIONS_STATE.currentOperationId,op=OPERATIONS_STATE.currentOperation; if(!op){showToast('❌ افتح العملية','error');return;} var f=OPERATIONS_STATE.currentFunding,p=OPERATIONS_STATE.currentProfits; var at=_getVal('opDynamicActionType'); showLoading(); try{
if(at==='client_funding'){ if(op.is_locked||op.status!=='active'){showToast('❌ غير نشطة/مقفلة','error');hideLoading();return;} var fa=parseFloat(_getVal('opFundAmount'))||0; if(fa<=0){showToast('❌ مبلغ غير صحيح','error');hideLoading();return;} if(fa>f.remainingClientFunding+0.01){showToast('❌ يتجاوز المتبقي','error');hideLoading();return;} await _createTransfer({type:'company_to_client',purpose:'client_funding',operation_id:opId,client_id:op.client_id,investor_id:null,amount:fa,transfer_date
