// ============================================================
// نظام إدارة التمويل - Transfers Module (Parties Ledger)
// Version: 6.2.2
// v6.2.2: P2-1 - فرض سقوف مالية على المسار اليدوي باستخدام الـ Core
// ============================================================
var TRANSFERS_STATE={search:'',filter:'',records:[],referenceCache:{clients:null,investors:null,operations:null},listCache:{lastLoad:null,records:null}};
var TRANSFER_FLOW_MAP=Object.freeze({
 'company_to_client':{party_type:'client',transaction_category:'client_deposit_in',transfer_type:'company_to_client',purpose_options:['client_funding','additional_funding','settlement','other'],label:'تمويل عميل'},
 'client_to_company':{party_type:'client',transaction_category:'client_use_out',transfer_type:'client_to_company',purpose_options:['client_repayment','settlement','other'],label:'سداد من عميل'},
 'company_to_investor':{party_type:'investor',transaction_category:'investor_return_out',transfer_type:'company_to_investor',purpose_options:['capital_return','profit_distribution','settlement','other'],label:'تحويل لممول'},
 'investor_to_company':{party_type:'investor',transaction_category:'investor_capital_in',transfer_type:'investor_to_company',purpose_options:['capital_funding','client_funding','settlement','other'],label:'إيداع من ممول'},
 'client_to_investor':{party_type:'client',transaction_category:'client_to_investor',transfer_type:'client_to_investor',purpose_options:['settlement','other'],label:'تحويل من عميل لممول'},
 'investor_to_client':{party_type:'investor',transaction_category:'investor_to_client',transfer_type:'investor_to_client',purpose_options:['settlement','other'],label:'تحويل من ممول لعميل'}});
var WORKFLOW_TRANSFER_PURPOSES=Object.freeze(['client_repayment','capital_return','profit_distribution']);
var PURPOSE_TEXT_AR=Object.freeze({client_funding:'تمويل',capital_funding:'تمويل رأس مال',client_repayment:'سداد',capital_return:'إرجاع رأس مال',profit_distribution:'توزيع أرباح',settlement:'تسوية',additional_funding:'تمويل إضافي',other:'أخرى'});
if(typeof window!=='undefined')window.PURPOSE_TEXT_AR=PURPOSE_TEXT_AR;
function initTransfers(){ registerScreenLoader('transfers',loadTransfers); }
async function loadTransfers(){ if(!isSupabaseReady())return; showLoading(); try{ var r=await runQuery(function(){ var q=APP.supabase.from('transfers').select('id, reference_number, type, purpose, operation_id, client_id, investor_id, amount, transfer_date, notes, party_type, transaction_category, is_archived, created_at').order('transfer_date',{ascending:false}); if(TRANSFERS_STATE.filter)q=q.eq('party_type',TRANSFERS_STATE.filter); if(TRANSFERS_STATE.search){var s='%'+TRANSFERS_STATE.search+'%';q=q.or('reference_number.ilike.'+s+',notes.ilike.'+s);} return q; },{context:'loadTransfers',throwError:true});
 var c=await loadClientsForTransfers(),i=await loadInvestorsForTransfers(),o=await loadOperationsForTransfers(); var idx=buildTransfersIndexes(c,i,o); var ts=r.data||[]; ts.forEach(function(t){ t.client=t.client_id?idx.clientsById[t.client_id]:(t.operation_id&&idx.operationsById[t.operation_id]?idx.clientsById[idx.operationsById[t.operation_id].client_id]:null); t.investor=t.investor_id?idx.investorsById[t.investor_id]:null; t.operation=t.operation_id?idx.operationsById[t.operation_id]:null; }); TRANSFERS_STATE.records=ts; renderTransfersList(); } catch(e){ showToast(handleSupabaseError(e,'تحميل التحويلات'),'error'); } finally { hideLoading(); } }
async function loadClientsForTransfers(){ if(TRANSFERS_STATE.referenceCache.clients)return TRANSFERS_STATE.referenceCache.clients; var r=await runQuery(function(){return APP.supabase.from('clients').select('id, name, is_archived').order('name');},{context:'loadClientsForTransfers',throwError:true}); TRANSFERS_STATE.referenceCache.clients=r.data||[]; return TRANSFERS_STATE.referenceCache.clients; }
async function loadInvestorsForTransfers(){ if(TRANSFERS_STATE.referenceCache.investors)return TRANSFERS_STATE.referenceCache.investors; var r=await runQuery(function(){return APP.supabase.from('investors').select('id, name, is_archived').order('name');},{context:'loadInvestorsForTransfers',throwError:true}); TRANSFERS_STATE.referenceCache.investors=r.data||[]; return TRANSFERS_STATE.referenceCache.investors; }
async function loadOperationsForTransfers(){ if(TRANSFERS_STATE.referenceCache.operations)return TRANSFERS_STATE.referenceCache.operations; var r=await runQuery(function(){return APP.supabase.from('operations').select('id, name, client_id, amount, status, is_locked, is_archived').order('name');},{context:'loadOperationsForTransfers',throwError:true}); TRANSFERS_STATE.referenceCache.operations=r.data||[]; return TRANSFERS_STATE.referenceCache.operations; }
function buildTransfersIndexes(c,i,o){ var cb={},ib={},ob={}; (c||[]).forEach(function(x){cb[x.id]=x;}); (i||[]).forEach(function(x){ib[x.id]=x;}); (o||[]).forEach(function(x){ob[x.id]=x;}); return {clientsById:cb,investorsById:ib,operationsById:ob}; }
function renderTransfersList(){ var c=document.getElementById('transfersTable'); if(!c)return; if(!TRANSFERS_STATE.records.length){c.innerHTML='<div class="empty-state">لا توجد تحويلات</div>';return;} var h='<table><thead><tr><th>الرقم</th><th>التاريخ</th><th>من</th><th>إلى</th><th>الغرض</th><th>المبلغ</th><th>العملية</th><th>إجراءات</th></tr></thead><tbody>'; TRANSFERS_STATE.records.forEach(function(t){ h+='<tr><td>'+escapeHtml(t.reference_number||'-')+'</td><td>'+formatDate(t.transfer_date)+'</td><td>'+_getFromText(t)+'</td><td>'+_getToText(t)+'</td><td>'+(PURPOSE_TEXT_AR[t.purpose]||t.purpose)+'</td><td>'+formatMoney(t.amount)+'</td><td>'+escapeHtml(t.operation?t.operation.name:'-')+'</td><td class="actions-cell">'+(canEdit()?'<button class="btn btn-secondary btn-sm" data-action="editTransfer" data-param="'+t.id+'">✏️</button> <button class="btn btn-danger btn-sm" data-action="deleteTransfer" data-param="'+t.id+'">🗑️</button>':'')+'</td></tr>'; }); c.innerHTML=h+'</tbody></table>'; }
function _getFromText(t){ switch(t.type){ case 'company_to_client': case 'company_to_investor': return '🏢 الشركة'; case 'client_to_company': case 'client_to_investor': return t.client?'<a href="#" data-action="openClientFile" data-param="'+t.client.id+'">'+escapeHtml(t.client.name)+'</a>':'عميل'; case 'investor_to_company': case 'investor_to_client': return t.investor?'<a href="#" data-action="openInvestorFile" data-param="'+t.investor.id+'">'+escapeHtml(t.investor.name)+'</a>':'ممول'; default: return '-'; } }
function _getToText(t){ switch(t.type){ case 'client_to_company': case 'investor_to_company': return '🏢 الشركة'; case 'company_to_client': case 'investor_to_client': return t.client?'<a href="#" data-action="openClientFile" data-param="'+t.client.id+'">'+escapeHtml(t.client.name)+'</a>':'عميل'; case 'company_to_investor': case 'client_to_investor': return t.investor?'<a href="#" data-action="openInvestorFile" data-param="'+t.investor.id+'">'+escapeHtml(t.investor.name)+'</a>':'ممول'; default: return '-'; } }
function _buildAllPartiesOptions(){ var o='<option value="">-- اختر الحساب --</option><option value="company:company" data-type="company">🏢 الشركة</option>'; var c=TRANSFERS_STATE.referenceCache.clients||[]; if(c.length){o+='<optgroup label="👤 العملاء">'; c.forEach(function(x){if(!x.is_archived)o+='<option value="client:'+x.id+'" data-type="client">👤 '+escapeHtml(x.name)+'</option>';}); o+='</optgroup>';} var i=TRANSFERS_STATE.referenceCache.investors||[]; if(i.length){o+='<optgroup label="💼 الممولين">'; i.forEach(function(x){if(!x.is_archived)o+='<option value="investor:'+x.id+'" data-type="investor">💼 '+escapeHtml(x.name)+'</option>';}); o+='</optgroup>';} return o; }
function _parsePartyValue(v){ if(!v)return{type:null,id:null}; var p=v.split(':'); return {type:p[0],id:p[1]}; }
function _determineTransferType(f,t){ return f+'_to_'+t; }

// ✅ P2-1: بناء بيانات العملية مع استبعاد التحويل الجاري تحريره
async function _buildOpCalcDataExcluding(opId,excludeId){
 var r=await Promise.all([
  runQuery(function(){return APP.supabase.from('operations').select('*').eq('id',opId).single();},{context:'cap-op',throwError:true}),
  runQuery(function(){return APP.supabase.from('operation_investors').select('id, investor_id, contribution, profit').eq('operation_id',opId);},{context:'cap-opinv',throwError:false}),
  runQuery(function(){return APP.supabase.from('transfers').select('id, type, purpose, operation_id, client_id, investor_id, amount, transfer_date').eq('operation_id',opId);},{context:'cap-trans',throwError:false})
 ]);
 var ts=(r[2].data||[]).filter(function(t){return t.id!==excludeId;});
 var idx={operationsById:{},opInvestorsByOperation:{},transfersByOperation:{}};
 if(r[0].data)idx.operationsById[opId]=r[0].data;
 idx.opInvestorsByOperation[opId]=r[1].data||[];
 idx.transfersByOperation[opId]=ts;
 return {operations:r[0].data?[r[0].data]:[],operationInvestors:r[1].data||[],transfers:ts,indexes:idx};
}
// ✅ P2-1: سقوف مالية للمسار اليدوي باستخدام الـ Core (بدون operation = بدون سقف)
async function _validateTransferCaps(fd){
 if(!fd.operationId) return {ok:true};
 var data=await _buildOpCalcDataExcluding(fd.operationId, fd.id);
 var f=getOperationFunding(fd.operationId,data);
 var p=getOperationProfits(fd.operationId,data);
 var amt=parseFloat(fd.amount)||0;
 var type=fd.fromType+'_to_'+fd.toType;
 var pi=null; f.perInvestor.forEach(function(x){ if(x.investorId===fd.investorId)pi=x; });
 if(type==='investor_to_company'){ if(pi&&amt>pi.remaining+0.01) return {ok:false,msg:'❌ المبلغ يتجاوز المتبقي للممول ('+formatMoney(pi.remaining)+')'}; }
 else if(type==='client_to_company'){ if(amt>p.clientOutstanding+0.01) return {ok:false,msg:'❌ المبلغ يتجاوز المستحق من العميل ('+formatMoney(p.clientOutstanding)+')'}; }
 else if(type==='company_to_client'){ if(amt>f.remainingClientFunding+0.01) return {ok:false,msg:'❌ المبلغ يتجاوز المتبقي لتمويل العميل ('+formatMoney(f.remainingClientFunding)+')'}; }
 else if(type==='company_to_investor'){
   if(fd.purpose==='capital_return'){ if(pi&&amt>pi.remainingCapital+0.01) return {ok:false,msg:'❌ المبلغ يتجاوز رأس المال المتبقي ('+formatMoney(pi.remainingCapital)+')'}; }
   else if(fd.purpose==='profit_distribution'){ if(pi&&amt>pi.remainingProfit+0.01) return {ok:false,msg:'❌ المبلغ يتجاوز الربح المتبقي ('+formatMoney(pi.remainingProfit)+')'}; }
 }
 return {ok:true};
}

async function openTransferModal(transferId,prefill){ if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;} var t=document.getElementById('transferModalTitle'); if(!t)return; await Promise.all([loadClientsForTransfers(),loadInvestorsForTransfers(),loadOperationsForTransfers()]); var f=document.getElementById('transferFromType'),o=document.getElementById('transferToType'),op=document.getElementById('transferOperation'); var all=_buildAllPartiesOptions(); if(f)f.innerHTML=all; if(o)o.innerHTML=all; if(op&&TRANSFERS_STATE.referenceCache.operations){ var os='<option value="">-- بدون عملية --</option>'; TRANSFERS_STATE.referenceCache.operations.forEach(function(x){if(!x.is_archived)os+='<option value="'+x.id+'">'+escapeHtml(x.name)+'</option>';}); op.innerHTML=os; } resetTransferForm(); if(transferId){ var r=await runQuery(function(){return APP.supabase.from('transfers').select('*').eq('id',transferId).single();},{context:'openTransferModal',throwError:true}); if(r.data)populateTransferForm(r.data,'تعديل تحويل'); } else { t.textContent='إضافة تحويل'; if(prefill)_applyPrefill(prefill); } openModal('transferModal'); }
function editTransfer(id){ openTransferModal(id); }
function updateTransferFields(){ var f=document.getElementById('transferFromType'),o=document.getElementById('transferToType'); if(!f||!o)return; var a=_parsePartyValue(f.value),b=_parsePartyValue(o.value); if(a.type&&b.type){ var flow=TRANSFER_FLOW_MAP[_determineTransferType(a.type,b.type)]; if(flow){ _updatePurposeField(a.type,b.type); updateTransferSummary(a.type,b.type); var fp=document.getElementById('transferFromParty'),tp=document.getElementById('transferToParty'),cat=document.getElementById('transferTransactionCategory'); if(fp)fp.value=a.type; if(tp)tp.value=b.type; if(cat)cat.value=flow.transaction_category; } } }
function _updatePurposeField(ft,tt){ var row=document.getElementById('transferPurposeRow'),sel=document.getElementById('transferPurpose'); if(!row){ var lbl=document.querySelector('#transferModal label[for="transferAmount"]'); if(!lbl)return; var g=lbl.closest('.form-group'); if(!g)return; row=document.createElement('div'); row.className='form-group'; row.id='transferPurposeRow'; row.innerHTML='<label for="transferPurpose">الغرض *</label><select id="transferPurpose"></select>'; g.parentNode.insertBefore(row,g); sel=document.getElementById('transferPurpose'); } if(!sel)return; var flow=TRANSFER_FLOW_MAP[ft+'_to_'+tt]; if(!flow){row.style.display='none';return;} var o=''; flow.purpose_options.forEach(function(pp){o+='<option value="'+pp+'">'+(PURPOSE_TEXT_AR[pp]||pp)+'</option>';}); sel.innerHTML=o; row.style.display='block'; }
function updateTransferSummary(ft,tt){ var el=document.getElementById('transferSummary'); if(!el)return; var flow=TRANSFER_FLOW_MAP[ft+'_to_'+tt]; if(!flow){el.style.display='none';return;} var f2=ft==='company'?'🏢 الشركة':(ft==='client'?'👤 عميل':'💼 ممول'); var t2=tt==='company'?'🏢 الشركة':(tt==='client'?'👤 عميل':'💼 ممول'); var sf=document.getElementById('summaryFrom'); if(sf)sf.textContent=f2; var st=document.getElementById('summaryTo'); if(st)st.textContent=t2; var sc=document.getElementById('summaryCategory'); if(sc)sc.textContent=flow.label; el.style.display='block'; }
function populateTransferForm(tr,title){ var t=document.getElementById('transferModalTitle'); if(t)t.textContent=title; _setTransVal('transferId',tr.id); var f=document.getElementById('transferFromType'),o=document.getElementById('transferToType'); if(f){ var fv=''; switch(tr.type){ case 'company_to_client': case 'company_to_investor': fv='company:company';break; case 'client_to_company': case 'client_to_investor': fv='client:'+tr.client_id;break; case 'investor_to_company': case 'investor_to_client': fv='investor:'+tr.investor_id;break; } f.value=fv; } if(o){ var tv=''; switch(tr.type){ case 'client_to_company': case 'investor_to_company': tv='company:company';break; case 'company_to_client': case 'investor_to_client': tv='client:'+tr.client_id;break; case 'company_to_investor': case 'client_to_investor': tv='investor:'+tr.investor_id;break; } o.value=tv; } updateTransferFields(); _setTransVal('transferAmount',tr.amount); _setTransVal('transferOperation',tr.operation_id); _setTransVal('transferDate',formatDateForInput(tr.transfer_date)); _setTransVal('transferNotes',tr.notes); setTimeout(function(){ if(tr.purpose)_setTransVal('transferPurpose',tr.purpose); },100); }
function resetTransferForm(){ ['transferId','transferFromType','transferToType','transferAmount','transferOperation','transferNotes','transferTransactionCategory','transferPurpose'].forEach(function(x){_setTransVal(x,'');}); _setTransVal('transferDate',getTodayDate()); var r=document.getElementById('transferPurposeRow'); if(r)r.style.display='none'; var s=document.getElementById('transferSummary'); if(s)s.style.display='none'; }
function _applyPrefill(p){ var f=document.getElementById('transferFromType'),o=document.getElementById('transferToType'); if(p.fromType&&p.fromEntity){if(f)f.value=p.fromType+':'+p.fromEntity;} else if(p.fromType==='company'){if(f)f.value='company:company';} if(p.toType&&p.toEntity){if(o)o.value=p.toType+':'+p.toEntity;} else if(p.toType==='company'){if(o)o.value='company:company';} updateTransferFields(); setTimeout(function(){ if(p.amount)_setTransVal('transferAmount',p.amount); if(p.operationId)_setTransVal('transferOperation',p.operationId); if(p.date)_setTransVal('transferDate',p.date); if(p.purpose)_setTransVal('transferPurpose',p.purpose); },150); }
function collectTransferFormData(){ var f=document.getElementById('transferFromType'),o=document.getElementById('transferToType'); var a=_parsePartyValue(f?f.value:''),b=_parsePartyValue(o?o.value:''); var cid=null,iid=null; if(a.type==='client')cid=a.id; else if(b.type==='client')cid=b.id; if(a.type==='investor')iid=a.id; else if(b.type==='investor')iid=b.id; var p=document.getElementById('transferPurpose'); return {id:_getTransVal('transferId'),fromType:a.type,fromId:a.id,toType:b.type,toId:b.id,clientId:cid,investorId:iid,operationId:_getTransVal('transferOperation'),amount:_getTransVal('transferAmount'),transferDate:_getTransVal('transferDate'),notes:_getTransVal('transferNotes').trim(),transactionCategory:_getTransVal('transferTransactionCategory'),purpose:p?p.value:''}; }
async function validateTransferForm(d){ if(!d.fromType||!d.toType){showToast('❌ اختر من وإلى','error');return false;} if(d.fromType===d.toType&&d.fromId&&d.fromId===d.toId){showToast('❌ لا تحويل لنفس الطرف','error');return false;} if(d.fromType==='company'&&d.toType==='company'){showToast('❌ شركة→شركة غير مسموح','error');return false;} var flow=TRANSFER_FLOW_MAP[d.fromType+'_to_'+d.toType]; if(!flow){showToast('❌ نوع غير مسموح','error');return false;} if(!isPositiveNumber(d.amount)){showToast('❌ مبلغ غير صحيح','error');return false;} if(isEmpty(d.transferDate)){showToast('❌ التاريخ مطلوب','error');return false;} return true; }
async function _assertOperationEditable(opId){ if(!opId)return true; var r=await runQuery(function(){return APP.supabase.from('operations').select('is_locked, status').eq('id',opId).single();},{context:'transfer-opLock',throwError:false}); if(!r.data)return true; return !(r.data.is_locked===true||r.data.status==='completed'||r.data.status==='cancelled'); }

async function saveTransfer(){ if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;} var d=collectTransferFormData(); if(!(await validateTransferForm(d)))return;
 var caps=await _validateTransferCaps(d); if(!caps.ok){ showToast(caps.msg,'error'); return; }   // ✅ P2-1
 var flow=TRANSFER_FLOW_MAP[d.fromType+'_to_'+d.toType]; var purpose=d.purpose||flow.purpose_options[0]; var data={type:flow.transfer_type,purpose:purpose,operation_id:d.operationId||null,client_id:d.clientId||null,investor_id:d.investorId||null,amount:parseFloat(d.amount),transfer_date:d.transferDate,notes:d.notes||null,party_type:flow.party_type,transaction_category:d.transactionCategory||flow.transaction_category}; showLoading(); try{ if(d.id){ var old=await runQuery(function(){return APP.supabase.from('transfers').select('*').eq('id',d.id).single();},{context:'saveTransfer-getOld',throwError:true}); var oldOp=old.data?old.data.operation_id:null; if(!(await _assertOperationEditable(oldOp))){showToast('❌ العملية مقفلة/منتهية - لا يمكن التعديل','error');hideLoading();return;} if(d.operationId&&d.operationId!==oldOp&&!(await _assertOperationEditable(d.operationId))){showToast('❌ العملية المقصودة مقفلة/منتهية','error');hideLoading();return;} await runQuery(function(){return APP.supabase.from('transfers').update(data).eq('id',d.id);},{context:'saveTransfer-update',throwError:true}); _logT('تعديل تحويل','transfer',d.id,JSON.stringify(old.data),JSON.stringify(data),'update'); showToast('✅ تم التحديث','success'); } else { var r=await runQuery(function(){return APP.supabase.from('transfers').insert(data).select();},{context:'saveTransfer-insert',throwError:true}); if(r.data&&r.data[0]){_logT('إضافة تحويل','transfer',r.data[0].id,null,JSON.stringify(data),'create'); showToast('✅ تم الإضافة','success');} } closeModal('transferModal'); loadTransfers(); refreshRelatedScreens(data.operation_id); } catch(e){ showToast(handleSupabaseError(e,'حفظ التحويل'),'error'); } finally { hideLoading(); } }
async function deleteTransfer(id){ if(!canEdit()){showToast('❌ لا توجد صلاحية','error');return;} var tr=TRANSFERS_STATE.records.find(function(x){return x.id===id;}); if(!tr){showToast('❌ غير موجود','error');return;} if(tr.operation_id&&!(await _assertOperationEditable(tr.operation_id))){showToast('❌ العملية مقفلة/منتهية - لا يمكن الحذف','error');return;} var msg=(WORKFLOW_TRANSFER_PURPOSES.indexOf(tr.purpose)!==-1||tr.operation_id)?'⚠️ تحويل مرتبط بسير العمل، حذفه يؤثر على الأرصدة.\nمتأكد؟':'حذف التحويل؟'; if(!confirmAction(msg))return; showLoading(); try{ var old=await runQuery(function(){return APP.supabase.from('transfers').select('*').eq('id',id).single();},{context:'deleteTransfer-getOld',throwError:true}); await runQuery(function(){return APP.supabase.from('transfers').delete().eq('id',id);},{context:'deleteTransfer',throwError:true}); _logT('حذف تحويل','transfer',id,JSON.stringify(old.data),null,'delete'); showToast('✅ تم الحذف','success'); loadTransfers(); refreshRelatedScreens(tr.operation_id); } catch(e){ showToast(handleSupabaseError(e,'حذف التحويل'),'error'); } finally { hideLoading(); } }
function _logT(a,et,ei,ov,nv,at){ if(typeof window.logActivityToDB==='function')window.logActivityToDB(a,et,ei,ov,nv,a,at); }
function refreshRelatedScreens(opId){ if(opId&&typeof loadOpInvestorsTab==='function')loadOpInvestorsTab(opId); if(typeof loadDashboard==='function'&&APP.currentScreen==='dashboard')loadDashboard(); if(typeof loadClients==='function'&&APP.currentScreen==='clients')loadClients(); if(typeof loadInvestors==='function'&&APP.currentScreen==='investors')loadInvestors(); }
function searchTransfers(t){ TRANSFERS_STATE.search=t||''; loadTransfers(); }
function filterTransfers(v){ TRANSFERS_STATE.filter=v||''; loadTransfers(); }
function getTransferTypeText(t){ var m={'company_to_client':'تمويل عميل (شركة ← عميل)','client_to_company':'سداد من عميل (عميل ← شركة)','company_to_investor':'تحويل لممول (شركة ← ممول)','investor_to_company':'إيداع من ممول (ممول ← شركة)','client_to_investor':'تحويل من عميل لممول','investor_to_client':'تحويل من ممول لعميل'}; return m[t]||t||'-'; }
function getPurposeText(p){ return PURPOSE_TEXT_AR[p]||p||'-'; }
if(typeof window!=='undefined'){ window.getTransferTypeText=getTransferTypeText; window.getPurposeText=getPurposeText; }
function _getTransVal(id){ var e=document.getElementById(id); return e?e.value:''; }
function _setTransVal(id,v){ var e=document.getElementById(id); if(e)e.value=(v!==null&&v!==undefined)?v:''; }
if(typeof document!=='undefined'){ initTransfers(); }
// ============================================================
// END OF TRANSFERS.JS (v6.2.2)
// ============================================================
